Repository elan-ev/opencast-studio, pull requests merged in 2019-11, with the labels that each got.

#216 Execute Tests on Travis CI
  .travis.yml
Labels: tests

#215 Introduce Test Deployments
  .travis-deploy-test.sh
  .travis.yml
Labels: tests

#214 Add `pre-release-testing` document describing the QA testing process
  doc/pre-release-testing.md
Labels: documentation

#229 Build date in test deployment
  .travis-deploy-test.sh
Labels: tests

#219 Add Security Policy
  SECURITY.md
Labels: documentation

#218 Add Contribution Guide
  CONTRIBUTING.md
Labels: documentation

#246 Fix Translation Keys
  src/ui/save-creation.js
  src/ui/toolbar.js
Labels: bug

#252 Updates Languages/Language Selector
  src/flags/germany.png
  src/flags/iran.png
  src/flags/license/license.pdf
  src/flags/united-kingdom.png
  src/languages.js
  src/ui/languages-chooser.js
  src/ui/languages-chosen.js
  src/ui/languages-flag.js
  src/ui/languages-item.js
  src/ui/languages-list.js
Labels: bug

#260 Fix Language Selector
  src/i18n/index.js
  src/languages.js
Labels: bug
