Repository elan-ev/opencast-studio, pull requests merged in 2023-11, with the labels that each got.

#1143 Add configurable series selection to upload step
  CONFIGURATION.md
  package-lock.json
  package.json
  src/i18n/locales/de.json
  src/i18n/locales/en.json
  src/opencast.tsx
  src/settings.tsx
  src/steps/finish/upload.tsx
Labels: type:new-feature

#1150 `npm audit fix`
  package-lock.json
Labels: type:dependencies, type:security

#1154 Adapt compatibility table to new features
  README.md
Labels: type:documentation
